# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "MeLo Lab"
title:              "MeLo Lab at the University of Utah"
description:        "The Mathematics of Language and Cognition Lab is a research group at the University of Utah."


# URL
url:                https://aniellodesanto.github.io//MeLo
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
#nav:
#  - name:           "home"
#    href:           "/"
#  - name:           "about"
#    href:           "/about"
#  - name:           "publications"
#    href:           "/publication"
#  - name:           "people"
#    href:           "/people"
#  - name:           "blog"
#    href:           "/blog"
#  - name:           "resources"
#    href:           "/resources"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
